<?php
// Generated by ZF2's ./bin/classmap_generator.php

return array(
  'WebSockets\Module'                               => __DIR__ .'Module.php',
  'WebSockets\Controller\WebsocketCLIController'    => __DIR__ .'/src/WebSockets/Controller/WebsocketCLIController.php',
  'WebSockets\Exception\ExceptionStrategy'          => __DIR__ .'/src/WebSockets/Exception/ExceptionStrategy.php',
  'WebSockets\Factory\ApplicationFactory'           => __DIR__ .'/src/WebSockets/Factory/ApplicationFactory.php',
  'WebSockets\Aware\ApplicationInterface'	    => __DIR__ .'/src/WebSockets/Aware/ApplicationInterface.php',
  'WebSockets\Service\WebsocketServer'              => __DIR__ .'/src/WebSockets/Service/WebsocketServer.php',
  'WebSockets\Status\WebSocketFrameCode'	    => __DIR__ .'/src/WebSockets/Status/WebSocketFrameCode.php',
  'WebSockets\Status\WinSocketErrors'		    => __DIR__ .'/src/WebSockets/Status/WinSocketErrors.php',
  'WebSockets\Status\UnixSocketErrors'		    => __DIR__ .'/src/WebSockets/Status/UnixSocketErrors.php',
  'WebSockets\Application\Chat'			    => __DIR__ .'/src/WebSockets/Application/Chat.php',
  'WebSockets\View\Helper\Socket'		    => __DIR__ .'/src/WebSockets/View/Helper/Socket.php',
);
